# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
inhibit_all_warnings!

target 'Reward' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  pod 'ObjectMapper'
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'

  # Pods for Reward

  target 'RewardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
